### ISSUE TITLE
Move strings to resources

### ISSUE THREAD

**Issue by EduFdezSoy** [EduFdezSoy/Manga2Kindle#17]
Move strings to `res/values/strings.xml` to be able to translate them later

**Comment by EduFdezSoy** [comment]
no need to translate anything, just grab a view and move the texts to the strings file, remember to comment in here what you done!

**Comment by fejd** [comment]
I can grab this one.

**Comment by fejd** [comment]
I've changed some strings from android:text to tools:text since they seemed to be mostly useful for the layout editor, as they were set in the views that loaded the layouts.
